    - name: Récupération des variables dynamiquement
      include_vars: "{{ item }}"
      with_first_found:
        - vars/webserver_vars_{{ ansible_os_family }}.yml
        - vars/webserver_vars.yml
    - name: Mise à jour du cache pour APT
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'
    - name: Package pour apache
      package: "name={{ webserver_apache_name }}"
    - name: Fichier index.html original
      template:
        dest: /var/www/html/index.html
        src: index.html.j2
      tags: [fichier]
    - name: Activation et démarrage du service
      service:
        name: "{{ webserver_apache_name }}"
        state: started
        enabled: yes
    - name: Ouverture du port 80 dans le pare-feu
      when: ansible_os_family == 'RedHat'
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: True
